### ISSUE TITLE
Fatal error: Class 'Dukt\OAuth\Providers\BaseProvider' not found

### ISSUE THREAD

**Issue by afairhurst** [dukt/craft-linkedin#1]
I'd be very grateful to receive your assistance with a PHP error that occurs when I try to add a provider to OAuth.

I've downloaded and installed OAuth from the Dukt site. Standalone, it works fine.

When I add the Linkedin plugin, found on the Dukt site, Craft throws a PHP error, when I try to view the OAuth admin page.

`Fatal error: Class 'Dukt\OAuth\Providers\BaseProvider' not found in /Users/username/Sites/sitename/craft/plugins/linkedin/providers/oauth/Linkedin.php on line 13`

Craft Personal: 2.5.2767
Craft CMS: 1.0.12250616
OAuth: 1.01

**Comment by afairhurst** [comment]
In [this comment](https://github.com/carlcs/craft-instagram/issues/1#issuecomment-193741727) Carlcs suggested I downgrade to [OAuth version 1.0.79](https://github.com/dukt/craft-oauth/releases/tag/1.0.79) as the provider plugins need to be upgraded before they'll work with OAuth 1.0.12250616.

**Comment by mattstein** [comment]
Thanks for calling this out, @afairhurst! Solved my problem as well.
